#!/usr/bin/env node

require('trace');
require('clarify');
require('source-map-support');
const { Buffer } = require('buffer');
const path = require('path');
const argv = require('minimist')(process.argv.slice(2));
const concat = require('concat-stream');
const explain = require('explain-error');
const ytSource = require('u-wave-source-youtube');
const scSource = require('u-wave-source-soundcloud');
const recaptchaTestKeys = require('recaptcha-test-keys');
const express = require('express');
const config = require('./dev-server-config.json');
const mailDebug = require('debug')('uwave:mail');

const testTransport = {
  name: 'test',
  version: '0.0.0',
  send(mail, callback) {
    mail.message.createReadStream().pipe(concat((message) => {
      mailDebug(mail.message.getEnvelope().to, message.toString('utf8'));
      callback(null, {
        envelope: mail.message.getEnvelope(),
        messageId: mail.message.messageId()
      });
    }));
  }
};

function tryRequire(file, message) {
  try {
    // eslint-disable-next-line import/no-dynamic-require
    const mod = require(file);
    return mod.default || mod;
  } catch (e) {
    throw explain(e, message);
  }
}

function getCorePath() {
  try {
    return path.dirname(require.resolve('u-wave-core/package.json'));
  } catch (err) {
    throw explain(err, 'Could not find the u-wave core module. Did you run `npm link u-wave-core`?');
  }
}

function loadDevModules() {
  const apiPath = path.join(__dirname, '../src');
  const corePath = path.join(getCorePath(), './src');
  require('@babel/register').default({
    plugins: [require('@babel/plugin-transform-modules-commonjs').default],
    only: [ p => p.startsWith(apiPath) || p.startsWith(corePath) ],
  });
  const uwave = tryRequire(
    'u-wave-core/src/index.js',
    'Could not find the u-wave core module. Did you run `npm link u-wave-core`?'
  );
  const { createHttpApi, createSocketServer } = require('../src');

  return { uwave, createHttpApi, createSocketServer };
}

function loadProdModules() {
  const uwave = tryRequire(
    'u-wave-core',
    'Could not find the u-wave core module. Did you run `npm link u-wave-core`?'
  );
  const { createHttpApi, createSocketServer } = require('../');

  return { uwave, createHttpApi, createSocketServer };
}

/**
 * üWave API development server.
 */
function start() {
  const port = argv.port || 6042;
  const watch = argv.watch || false;

  const {
    uwave,
    createHttpApi,
    createSocketServer,
  } = watch ? loadDevModules() : loadProdModules();

  const uw = uwave(config);

  uw.on('mongoError', (err) => {
    throw explain(err, 'Could not connect to MongoDB. Is it installed and running?');
  });

  uw.on('redisError', (err) => {
    throw explain(err, 'Could not connect to the Redis server. Is it installed and running?');
  });

  uw.source(ytSource, config.sources.youtube);
  uw.source(scSource, config.sources.soundcloud);

  const app = express();
  const server = app.listen(port, () => {
    console.log(`Now listening on ${port}`);
  });

  app.set('json spaces', 2);

  const apiUrl = '/api';
  const secret = Buffer.from('none', 'utf8');

  app.use(apiUrl, createHttpApi(uw, {
    recaptcha: { secret: recaptchaTestKeys.secret },
    secret,
    auth: config.auth,
    mailTransport: testTransport,
  }));

  createSocketServer(uw, {
    server,
    secret,
  });

  return app;
}

start();
